<H4> Exercise 5 - Using Numpy </H4>

This is an introduction to Numpy library broken into three sections 

 - Basics
 - Mathematics
 - Statistics

**Local Host Kernal**

http://localhost:8889/tree?token=82731dd28c15c72cee077cbc56940111571809deb75cf6f6

In [63]:
## Begin by importing Numpy
import numpy as np

In [76]:
print("Create this array with these values in")
print()

a = np.array([[1,1,1,1,1],[1,0,0,0,1],[1,0,9,0,1],[1,0,0,0,1],[1,1,1,1,1]])
print (a)

Create this array with these values in

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


The code block below creates two arrays 5x5 and 3x3, the third script incerts a 9 into the centre with the 1,1 (nb. the arrays start at 0).

The fourth script then takes the 3x3 and incerts this into the 5x5 array.

In [82]:
#fill a 5x5 array called output with 1s
output = np.ones((5,5), dtype='int32')
print ("A 5x5 Array")
print(output)

#fill a 3 x3 array called z with 0s
z = np.zeros((3,3))
print()
print("A 3x3 Array")
print(z)

#within the array created above, replace the central reference with the number 9
z[1,1] = 9
print()
print("Inserts a 9 into the centre")
print(z)

#in output (Lots of 1's), we are going to replace them with the contents of z (mostly 0s)
#We are filling from row value 1, up to one before the end of the rows (-1)
#We are filling from column value 1, up to one before the end of the columns (-1)
output[1:-1,1:-1] = z
print()
print("Inserts the z 3x3 array into the output 5x5 array")
print(output)

A 5x5 Array
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

A 3x3 Array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Inserts a 9 into the centre
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]

Inserts the z 3x3 array into the output 5x5 array
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


The next four code block show the challanges you can have when copying arrays, nb arrays are overwritten!

In [83]:
#First of all, a simply array called a
a = np.array([1,2,3])
print(a)

[1 2 3]


In [85]:
#Now create a copy of a and called b and change the first value to 100
a = np.array([1,2,3])
b = a
b[0] = 100

print(b)

[100   2   3]


In [86]:
#Now testing the same code, print a again. You should see that b and a have actually become the same thing, which could cause unexpected issues later. Another part of the system may need a as it was.
a = np.array([1,2,3])
b = a
b[0] = 100

print(a)


[100   2   3]


In [69]:
#in this example of the same idea if we explicitly say b is a copy of a (see line 2) then we don't have that potential issue.
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


**Mathematics**

For a lot more maths methods use the Numpy docs

https://docs.scipy.org/doc/numpy/reference/routines.math.html


This page walks you through what happens when you multiply matrices with the same dimensions as we used in the code above.

https://www.mathsisfun.com/algebra/matrix-multiplying.html

If you explore the documentation you’ll see the amount of mathematical methods available is huge.

https://numpy.org/devdocs/reference/generated/numpy.sin.html

In [70]:
a = np.array([1,2,3,4])
print(a)
#Everything that was in "a" has two added to it's value
a + 2
a - 2
a * 2
a / 2

[1 2 3 4]


array([0.5, 1. , 1.5, 2. ])

In [71]:
#create a new colum called "b" with the values you'll see below in
b = np.array([1,0,1,0])
#in the code below we have added 1 to the columns 0 and 2
a + b
print (a)


[1 2 3 4]


In [72]:
# Take the sin
## calculates the trigonometric sine of each element in an array. This method operates element-wise on an array and returns a new array containing the sine values of the input array's elements. It is beneficial in mathematical computations involving trigonometric operations.
np.sin(a)


array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [73]:
# Take the cos
## computes the cosine of each element in an array
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Matrix Multiplying

In [87]:
#fill a 2 x 3 matrix called a with 1s
a = np.ones((2,3))
print(a)

#fill b over 3 rows and 2 columns with the value 2
b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

**Statistics**

Other Numpy Array built-in methods (Called functions here)

https://www.programiz.com/python-programming/numpy/array-functions


In [88]:
# 3 x 2 array that just happens to be called stats. You could call it anything you want
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
#the min of that array
np.min(stats)

1

In [92]:
#the min of each row
np.min(stats, axis=1)

array([1, 4])

In [93]:
#the min of each column
np.min(stats, axis=0)

array([1, 2, 3])

In [94]:
#the sum of each column
np.sum(stats, axis=0)

array([5, 7, 9])

In [95]:
#the mean of each column
np.average(stats, axis=0)

array([2.5, 3.5, 4.5])